project:
  type: website
  output-dir: docs
  resources:
    - files/*
    - images/*

website:
  title: "Mery Touceda-Suárez"
  site-url: https://merytouceda.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: publications.qmd
        text: Publications
      - href: outreach.qmd
        text: Outreach
      - href: art.qmd
        text: Art
      - href: writing.qmd
        text: Writing
    right:
      - icon: rss
        href: writing.xml

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    lightbox: true
    respect-user-color-scheme: true
